### ISSUE TITLE
First(?) Kete extraction help/discussion

### ISSUE THREAD

**Issue by shermp** [walter/extraction_point#1]
Hi Walter,

I now have a Kete dump to try and extract data from, and I've reached my first hurdle.

I seem to be having a file permission error, and I don't know Docker well enough to be sure of where the problem is occurring. (Note, I'm running a fresh install of Ubuntu 18.04 in a VM)

When running the command `docker-compose run app mix extraction_point.load_sql ../2019-07-25T07-16-14-ketexxxxxxx-pg.sql`, I get the following error:

```
Status: Downloaded newer image for mdillon/postgis:11-alpine
Creating extraction_point_db_1 ... done
Building app
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 878, in run
  File "compose/cli/main.py", line 1333, in run_one_off_container
  File "compose/service.py", line 324, in create_container
  File "compose/service.py", line 360, in ensure_image_exists
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 159, in build
  File "site-packages/docker/utils/build.py", line 30, in tar
  File "site-packages/docker/utils/build.py", line 49, in exclude_paths
  File "site-packages/docker/utils/build.py", line 214, in rec_walk
  File "site-packages/docker/utils/build.py", line 214, in rec_walk
  File "site-packages/docker/utils/build.py", line 214, in rec_walk
  File "site-packages/docker/utils/build.py", line 184, in rec_walk
PermissionError: [Errno 13] Permission denied: '/home/kete/kete/extraction_point/docker/data/postgres'
[2781] Failed to execute script docker-compose
```
I'm not sure if this is an issue with the Docker configuration, or my user permissions. I'm running everything in `kete` home directory, as the `kete` user, and the `kete` user has permission to run docker.

Can you assist?

Thanks.

**Comment by shermp** [comment]
So, I got past that error by running docker-compose as `sudo`. Not something I would want to do on a production machine obviously, but good enough on a fresh throwaway VM.

Next lot of errors are as follows:
```
Unchecked dependencies for environment dev:
* inflex (Hex package)
  the dependency is not available, run "mix deps.get"
* ecto_sql (Hex package)
  the dependency is not available, run "mix deps.get"
* gettext (Hex package)
  the dependency is not available, run "mix deps.get"
* nimble_csv (Hex package)
  the dependency is not available, run "mix deps.get"
* jason (Hex package)
  the dependency is not available, run "mix deps.get"
* arbor (Hex package)
  the dependency is not available, run "mix deps.get"
* geo_postgis (Hex package)
  the dependency is not available, run "mix deps.get"
* sweet_xml (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_pubsub (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix (Hex package)
  the dependency is not available, run "mix deps.get"
* postgrex (Hex package)
  the dependency is not available, run "mix deps.get"
* plug_cowboy (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_ecto (Hex package)
  the dependency is not available, run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies
```

**Comment by shermp** [comment]
So a ` sudo docker-compose run app mix deps.get` solved that problem.

Next issue was loading the sql file from the parent directory. Got a `No such file or directory` error. Moved the sql file to the current directory, and solved that issue.

Current issue is `psql:2019-07-25T07-16-14-ketexxxxx-pg.sql:24: ERROR:  type "biginteger" does not exist`.
It seems the data type for a big integer in Postgresql is `bigint`. That might be an issue that needs resolving in https://github.com/walter/kete_extraction

I shall try a manual S&R for that datatype to see if I can proceed.
EDIT: Yep, that seemed to work. On to step/command two...

**Comment by shermp** [comment]
So, get part way through the `docker-compose run app mix ecto.migrate` step, then it stops with the following error:
```
02:02:27.286 [debug] QUERY OK source="extracted_still_images" db=50.3ms decode=0.1ms
SELECT e0."id", e0."extended_content" FROM "extracted_still_images" AS e0 WHERE (NOT (e0."extended_content" IS NULL)) []
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:366: Enum.any?/2
    lib/extraction_point/extended_field/parse.ex:270: ExtractionPoint.ExtendedField.Parse.extract_choice_label_value/3
    lib/extraction_point/extended_field/parse.ex:253: ExtractionPoint.ExtendedField.Parse.fetch_choice_labelled_value_map/3
    lib/extraction_point/extended_field/parse.ex:132: ExtractionPoint.ExtendedField.Parse.extract_update_pair/2
    lib/extraction_point/data_change/table.ex:62: anonymous fn/3 in ExtractionPoint.DataChange.Table.build_updates/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/extraction_point/data_change/table.ex:26: anonymous fn/3 in ExtractionPoint.DataChange.Table.load_data_to_new_columns_from_extended_content/2
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:783: Enum.each/2
    priv/repo/migrations/20190614075006_extract_still_images.exs:52: ExtractionPoint.Repo.Migrations.ExtractStillImages.up/0
    (ecto_sql) lib/ecto/migration/runner.ex:272: Ecto.Migration.Runner.perform_operation/3
    (stdlib) timer.erl:166: :timer.tc/1
    (ecto_sql) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/7
    (ecto_sql) lib/ecto/migrator.ex:276: Ecto.Migrator.attempt/7
    (ecto_sql) lib/ecto/migrator.ex:176: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto_sql) lib/ecto/migrator.ex:258: anonymous fn/3 in Ecto.Migrator.run_maybe_in_transaction/6
    (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
```
This is the point where I have no idea what to try next...

**Comment by shermp** [comment]
Ah, so I THINK the problem lies in the following bit of code:
```
def load_data_to_new_columns_from_extended_content(extended_fields, table_name) do
    table_name
    |> query()
    |> Repo.all()
    |> Enum.each(fn row ->
      updates = build_updates(row, extended_fields)

      if not is_nil(updates) and Enum.any?(updates) do
        # run updates per row
        from(t in table_name,
          update: [set: ^updates],
          where: t.id == ^row.id
        )
        |> Repo.update_all([])
      end
    end)
  end
```
And would occur if the SQL query returned no rows from the database, and then tries to iterate over a non-existent set of rows.

**Comment by walter** [comment]
Hey @shermp!

Just seeing this thread now. I guess I forgot to set up watching on this repo. I thought as the creator, it would have been on by default. Anyway, sorry about taking so long to get back to you.

> So, I got past that error by running docker-compose as sudo. Not something I would want to do on a production machine obviously, but good enough on a fresh throwaway VM.

Great to see you are making headway and finding solutions yourself. Surprised you have to use `sudo` to create that directory, but perhaps it has to do with an assumption I had that you would be in a normal directory on your workstation rather than a vm. Might be something that can be I can tweak in the docker configuration to create the directory by default.

> So a `sudo docker-compose run app mix deps.get` solved that problem.

I think this has to do with previous `sudo` essentially starting things from a fresh docker session. I.e. the initial elixir container has a `mix deps.get` in its `Dockerfile`.

> Current issue is psql:2019-07-25T07-16-14-ketexxxxx-pg.sql:24: ERROR: type "biginteger" does not exist.

That should be taken care of with https://github.com/walter/kete_extraction/commit/db0b707c703abe8a3ca1a76a65ec4f1453a91b3e - might be Andy didn't refresh his copy of `kete_extraction` with that version before running it.

> (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom

I think the problem is that something to do with extended fields enumerable is being set to `:nil` rather than `nil`. Maybe we can touch base and I can take a look at the data dump and see if we can deal with it. I'll email you.

**Comment by shermp** [comment]
Thanks for the reply. @walter 

That last error is where I got all stopped, as I know nothing about Elixir (In fact, I'd never heard of it until now!), so wasn't sure where to go looking or how to fix.

**Comment by walter** [comment]
Thanks for the data. With its help I found the issue. If you pull the latest commit from master, I believe you should be able to run `docker-compose run app mix ecto.migrate` successfully. It should just continue where it left off (migrations rollback to starting db state if they encounter to an error while running).

**Comment by shermp** [comment]
Thank you very much @walter 

I now have the needed extracts. It was all smooth sailing after the migration phase was complete.
